[server]
host = "localhost"
port = 8080
siteName = "Better Battleships"
baseUrl = "http://localhost:8080"

[game]
limit = 8
idLength = 6
joinTimeout = 5000
rejoinTimeout = 30000
startWaitDuration = 5000

[parsing]
maxFileSize = 50000
maxFieldsSize = 256

[evaluation]
actionLimit = 25

[stats]
resultsPerPage = 20

[sql]
host = ""
user = ""
password = ""
database = ""
connectionLimit = 1

[auth]
hashRounds = 10
jwtSecretToken = ""
jwtExpiryTime = ""
